### ISSUE TITLE
Convert to `typing.NamedTuple`

### ISSUE THREAD

**Issue by nstarman** [glass-dev/glass#125]
https://github.com/glass-dev/glass/blob/c9a816dbbee8bccf8f9da5430fbb59e104c62f6d/glass/shells.py#L80

```python

class RadialWindow(NamedTuple):
    """Docstring."""

    attr1: float
    """Description."""

    attr2: float
    """Description."""

**Comment by ntessore** [comment]
Good catch. I was thinking whether a dataclass might not be better, but there probably are still a few cases of `for za, wa, zeff in radial_windows` scattered around.

**Comment by paddyroddy** [comment]
This is being tackled in #232, closing for now

**Comment by paddyroddy** [comment]
I went for `typing.NamedTuple` over `dataclasses.dataclass` as it involved fewer code changes
