### ISSUE TITLE
Generate multiple related fields

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#134]
There is a common request for biased tracers of the matter field using the same `alm` with differently-scaled `gls`.

This could be implemented if `generate_gaussian()` accepted either

* a sequence of `gls`, or
* `gls` with a leading axis.

The former option is potentially easier for users to provide, since those would be generated simply by calling e.g. `lognormal_gls()` multiple times with different inputs.

CC: @hangqianjun

**Comment by arthurmloureiro** [comment]
Sorry for jumping in here: 

I think that changing to add the bias prior to generating the alms, aka by rescaling the cls, we lose the ability to generate multiple tracers with different biases and the same underlying matter density field. But maybe I don't quite understand what is being proposed.

**Comment by ntessore** [comment]
The proposal is to generate the matter field as normal, but add functions to easily imprint a new (e.g. biased) angular power spectrum on the same alms. This isn't really a good bias model, but can be useful in some exceptional cases. See the [proposed example](https://github.com/glass-dev/glass-examples/blob/update/examples/basic/biased_lognormal.py) for the application.
