### ISSUE TITLE
NumPy 2 compatibility (+ drop `3.9` support)

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#163]
Ensure compatibility with the NumPy 2 release.

**Comment by paddyroddy** [comment]
Going to start this with the help of https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy

**Comment by paddyroddy** [comment]
- [ ] when done can remove the associated `# type: ignore[attr-defined]` comments for #308

**Comment by paddyroddy** [comment]
Have updated the title to reflect the fact that we will need to drop `3.9` to support `NumPy v2.1`
