### ISSUE TITLE
Change `CITATION.md` to `CITATION.cff`

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#175]
It's a dedicated file format designed to promote code as research https://citation-file-format.github.io, but can also promote papers using the `preferred` syntax

**Comment by ntessore** [comment]
I don't find .cff files at all useful, since no one in our field would know what to do with them. Let's do a .bib file with bibtex from ADS: https://ui.adsabs.harvard.edu/abs/2023OJAp....6E..11T/exportcitation

**Comment by Saransh-cpp** [comment]
The .cff format will enable copy-pastable citation in a dropdown menu on github, offering both APA and BibTex formats -

<img width="383" alt="image" src="https://github.com/user-attachments/assets/fb71b7b0-9327-4a81-a3b2-7d4cba4fb14b">

This has become a standard for software citations, but I'll also be happy to convert the .md file to a .bib file.

**Comment by ntessore** [comment]
That's pretty cool, but I would rather not lose the extra metadata from the ADS entry,

**Comment by paddyroddy** [comment]
> The .cff format will enable copy-pastable citation in a dropdown menu on github, offering both APA and BibTex formats -
> <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/74055102/367257629-fb71b7b0-9327-4a81-a3b2-7d4cba4fb14b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzE1ODIsIm5iZiI6MTcyNjU3MTI4MiwicGF0aCI6Ii83NDA1NTEwMi8zNjcyNTc2MjktZmI3MWI3YjAtOTMyNy00YTgxLWEzYjItN2Q0Y2JhNGZiMTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDExMDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YmI2NTYzOTAxMDRiZmVjNjZkMWQ1NzBiOTFmYTk0YzkzMWM5N2M4ODExMmNhYmY3OTdjMjcxZTk5Y2FjZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LmAJs3MolY4nlygAvgMZatGyDiCOqcNr0d5eBbu56zY">
> 
> This has become a standard for software citations, but I'll also be happy to convert the .md file to a .bib file.

Wouldn't a `CITATION.cff`, which only refers to the paper, be useful to benefit from this GitHub feature? An easy way to get a citation that you might not get otherwise. Can always also include a paper citation in the README [like this](https://github.com/astro-informatics/sleplet/blob/782279ec1be404aa356c6e0b583bd536cf3a4789/README.md?plain=1#L118-L133).

**Comment by Saransh-cpp** [comment]
Having a BibTex entry in the README and a `.cff` file to enable GitHub's feature sounds better imo. PyBaMM ([BibTex in README](https://github.com/pybamm-team/PyBaMM?tab=readme-ov-file#-citing-pybamm), [.cff file for GitHub](https://github.com/pybamm-team/PyBaMM/blob/develop/CITATION.cff)) does the same too. I'll reopen this issue for more discussion.

**Comment by paddyroddy** [comment]
Discussed in meeting and will adapt to `CITATION.cff`
