### ISSUE TITLE
Register `glass` on TestPyPI

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#178]
TestPyPI is a standalone server which allows one to double-check the package works as expected before pushing to PyPI. However, you need to specifically sign up to it (with a different API key) to benefit from it. Having PyPI alone doesn't guarantee you the appropriate TestPyPI.

**Comment by ntessore** [comment]
Registered on TestPyPI now.

**Comment by paddyroddy** [comment]
> Registered on TestPyPI now.

Cheers! Will incorporate in a workflow soon
