### ISSUE TITLE
Add `zenodo` integration

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#179]
Related to #175, add `zenodo` integration which allows one to attribute a DOI to the code itself (like a paper) https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content#issuing-a-persistent-identifier-for-your-repository-with-zenodo

**Comment by ntessore** [comment]
I am aware of Zenodo, and it is great for code. In this case, I would rather have people cite the GLASS paper, and not potentially only the DOI for the code or even version that they use.

**Comment by paddyroddy** [comment]
Okay. However, if you ever want to submit to [JOSS](https://joss.theoj.org) or [pyOpenSci](https://www.pyopensci.org) then you'll need it. Possibly for other journals which require archived code.
