### ISSUE TITLE
Make the repository Scientific Python compliant

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#187]
See https://learn.scientific-python.org/development/guides/repo-review/?repo=glass-dev%2Fglass&branch=main for all the missing things. Not all of them _must_ be added, but most of them should be.

**Comment by Saransh-cpp** [comment]
This can be closed now. The only failing checks from repo-review are -

1. [PY007](https://learn.scientific-python.org/development/guides/tasks#PY007): Supports an easy task runner (nox or tox)
  We don't want this as our testing infrastructure is simple enough.
2. [GH212](https://learn.scientific-python.org/development/guides/gha-basic#GH212): Require GHA update grouping
  Getting rid of dependabot in #174 
3. [PC140](https://learn.scientific-python.org/development/guides/style#PC140): Uses a type checker, [MY100](https://learn.scientific-python.org/development/guides/style#MY100): Uses MyPy (pyproject config), and related checks...
  Being tracked in #280 and #246
4. [PC160](https://learn.scientific-python.org/development/guides/style#PC160): Uses a spell checker
  We don't want one permanently in our repository.

**Comment by paddyroddy** [comment]
> This can be closed now. The only failing checks from repo-review are -
> 
>     1. [PY007](https://learn.scientific-python.org/development/guides/tasks#PY007): Supports an easy task runner (nox or tox)
>        We don't want this as our testing infrastructure is simple enough.

I'm not sure if I agree with this, `tox` is very simple to set up (not used `nox` myself). But I agree it is not urgent either way.

**Comment by Saransh-cpp** [comment]
I can create an issue for this for later.
