### ISSUE TITLE
Change dependencies to `~-` syntax rather than `>=`

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#189]
My concern is for example `NumPy` now has v2 (#163), the current syntax would allow that when the code doesn't necessarily support it yet.

**Comment by Saransh-cpp** [comment]
Would make sense to do this for NumPy, but I'd prefer not doing it for other dependencies - [Should You Use Upper Bound Version Constraints?](https://iscinumpy.dev/post/bound-version-constraints/)

**Comment by paddyroddy** [comment]
Addressed in #207, can close for now as this issue itself isn't that important
