### ISSUE TITLE
Remove legacy random number generation

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#208]
### Is Your Feature Request Related to a Problem? Please Describe

See explanation here https://docs.astral.sh/ruff/rules/numpy-legacy-random, have verified on the codebase with `ruff check --select NPY002 .`, there are 12 errors at the moment. These had support dropped from `numpy==1.16`

### Describe the Solution You'd Like

Use syntax like this instead
```python
rng = np.random.default_rng(1337)
rng.normal()
```

**Comment by ntessore** [comment]
We generally have `rng` support for all user functions, so these should be "safe" to update in examples and tests only.

Random number generation more widely will be one of the issues to solve for generic array support, so might be good to keep that in mind as well.
