### ISSUE TITLE
ModuleNotFoundError: No module named 'glass.ext.camb'

### ISSUE THREAD

**Issue by AlexMaraio** [glass-dev/glass#219]
### Describe the Bug

Hi all,

I'm just trying to use the "[plot_s4_galaxies.py](https://glass.readthedocs.io/projects/examples/stable/_downloads/619c02af4769b9030a8fc91b08aa0a46/plot_s4_galaxies.py)" example as provided with GLASS, but I'm running into a module not found error.

I'm running GLASS from a fresh Python installation, so my environment should be clean. 
To start, I create a new Conda environment with some default scientific Python packages
`conda create -c conda-forge jupyter ipython matplotlib scipy numpy pandas seaborn -n GLASS_Env`

Then activate: `conda activate GLASS_Env`.

Then install CAMB & GLASS `pip install camb glass`

Then finally run the `plot_s4_galaxies.py` example and get hit by the `ModuleNotFoundError` straight away.

Let me know if I can help debug from my end in any way.
Thanks!

### To Reproduce

```python
import glass.ext.camb
```

### Expected Behaviour

`glass.ext.camb` to be imported!

### Actual Behaviour

`glass.ext.camb` is not found!

```
Traceback (most recent call last):
  File "/home/maraio/Code/GLASS_examples/plot_s4_galaxies.py", line 44, in <module>
    import glass.ext.camb
ModuleNotFoundError: No module named 'glass.ext.camb'
```

### Version In Use

2024.1

### Additional Context

```markdown
- Python version: Python 3.12.5| packaged by conda-forge | (main, Aug  8 2024, 18:36:51) [GCC 12.4.0] on linux
- Operating system: Ubuntu 22.04.4 LTS x86_64
```

**Comment by ntessore** [comment]
Hi Alex, can you try and `pip install glass.ext.camb` as suggested [here](https://glass.readthedocs.io/projects/examples/stable/)? This will hopefully fix the issue!

**Comment by AlexMaraio** [comment]
Ah, sorry must have missed that on the examples page! 

Yep that's worked a treat, thanks again! :)

**Comment by ntessore** [comment]
No worries, it's too easy to miss currently. Try the new examples page that is integrated into the main documentation: https://glass.readthedocs.io/latest/examples.html

(Those are the "latest" docs, for the as-yet-unreleased GLASS version, compared to the "stable" docs of the latest GLASS release, which you get by default.)
