### ISSUE TITLE
Is `test_fits.py::test_out_filename` meant to utilise `tmp_path`?

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#238]
### Describe the Bug

The test https://github.com/glass-dev/glass/blob/a101ab48d8e9fcc6be5dc3fdc491afe971beda4e/tests/test_fits.py#L93-L99 has `tmp_path` fixture but isn't using it. Is this intentional or an oversight?

### To Reproduce

```python
import glass
...
```

### Version In Use

2024.2.dev38+gd9ced9d.d20240918

**Comment by ntessore** [comment]
Definitely an oversight, and probably how we ended up with `*.Fits` (with wrong case) in .gitignore. Can we fix the test, the `filename`, and `.gitignore`? :)

**Comment by paddyroddy** [comment]
Of course!
