### ISSUE TITLE
`test_fits.py::test_out_filename` is accessing private functions from the `fitsio` library

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#239]
### Describe the Bug

This is bad practice, as the external code cannot guarantee keeping internal functions with a consistent API. Are we happy with this? https://github.com/glass-dev/glass/blob/f7cedc9e5289f0505a15aff742ca0ff8bb4c180e/tests/test_fits.py#L93-L99

### To Reproduce

```python
import glass
...
```

### Version In Use

2024.2.dev41+ga3f00f2.d20240918

**Comment by ntessore** [comment]
Yeah, we can use `get_filename()` to obtain the same thing.

**Comment by Saransh-cpp** [comment]
I couldn't find a `get_filename()` in fitsio. Is the function somewhere else or am I missing something?
