### ISSUE TITLE
Do we need the licence section at the top of every file?

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#240]
### What is the Topic of Your Question

Other

### Add Your Question Below

This feels like a relic from the pre-git days, the licence file at the top level is sufficient and covers from a legal point of view (pretty sure)

**Comment by ntessore** [comment]
Pretty sure that is only part of the GPL.

**Comment by paddyroddy** [comment]
> Pretty sure that is only part of the GPL.

Yeah, I thought you were using MIT?

**Comment by ntessore** [comment]
Oh, I see! You want to _remove_

    # author: Nicolas Tessore <n.tessore@ucl.ac.uk>
    # license: MIT

from the existing files? Fine by me!

I thought you wanted to _add_ a blurb like

```
# Heracles: Euclid code for harmonic-space statistics on the sphere
#
# Copyright (C) 2023-2024 Euclid Science Ground Segment
#
# This file is part of Heracles.
#
# Heracles is free software: you can redistribute ...
```

to all files.

**Comment by paddyroddy** [comment]
Yeah, removal is what I meant, sorry that wasn't clear

**Comment by ntessore** [comment]
Plenty clear, sorry for the confusion
