### ISSUE TITLE
Use `numpy.typing` instead of `numpy.ndarray`

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#246]
### Is Your Feature Request Related to a Problem? Please Describe

This allows greater control of the type of a specific NumPy array https://numpy.org/doc/stable/reference/typing.html

**Comment by ntessore** [comment]
Yeah, good idea. Most of the typing in this code is non-functional, but it would be great to get it to pass MyPy and PyRight. This could be very helpful in spotting bugs when we implement the generic API.
