### ISSUE TITLE
rename galaxy ellipticity fields

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#25]
At the moment, the variable for unlensed galaxy ellipticity is `gal_ell`, and for lensed it is `gal_she`. I would like to change this to be `gal_eps` in both cases.  The lensing generator would then also return another field `gal_eps_src` that contains the unlensed source ellipticity.

This would enable generators which work on either the lensed or the unlensed ellipticities, depending on whether they occur before or after the lensing generator.

**Comment by ntessore** [comment]
Tagging @arthurmloureiro and @mwiet in case it causes problems in existing code.

**Comment by arthurmloureiro** [comment]
That seems like a good idea. I'd also say to add this to the documentation.

Are we planning on documenting all variable names and generators linked to them in some form?

**Comment by ntessore** [comment]
Definitely planned, the only thing it needs is a volunteer

**Comment by arthurmloureiro** [comment]
👀 

I'll think of something!
I first need to go through it all to see all the variable names, etc

**Comment by mwiet** [comment]
Seems like a good idea! I'll make sure to update everything accordingly. I can also help with the documentation, if needed.

**Comment by ntessore** [comment]
I am starting to think this would lead to the same sort of problems if someone wanted to access the unlensed source ellipticities when there is/isn't lensing in the simulation.

So perhaps best to keep it as "galaxy ellipticities" for the unlensed ones and "galaxy shears" for the lensed ones. This naming also makes it easier to discuss in the paper.
