### ISSUE TITLE
Why there are some negative value of gal_lon in glass.points.positions_from_delta？

### ISSUE THREAD

**Issue by z20230220** [glass-dev/glass#256]
### What is the Topic of Your Question

Usage

### Add Your Question Below

Hello Development Team,

I am currently using GLASS to generate galaxies, as demonstrated in the [example](https://glass.readthedocs.io/projects/examples/stable/basic/plot_density.html#sphx-glr-basic-plot-density-py). However, I have encountered an issue where some negative values for gal_lon are being produced by glass.points.positions_from_delta. Typically, the expected range for gal_lon should be [0, 360]. Although these negative values yield positions on the sphere that appear acceptable when adjusted by adding 360 degrees, their existence still seems somewhat unusual. Could you please explain the reason for this?

I would appreciate any assistance you could provide regarding this matter. The relevant code is as follows:

```
import numpy as np

# use the CAMB cosmology that generated the matter power spectra
import camb
from cosmology import Cosmology

# GLASS imports: matter, random fields, random points, galaxies
import glass.ext.camb
import glass.shells
import glass.fields
import glass.points
import glass.galaxies

# cosmology for the simulation
H0 = 67.74
omch2 = 0.11933
ombh2 = 0.02242

# basic parameters of the simulation
lmax = 1000

# set up CAMB parameters for matter angular power spectrum
pars = camb.set_params(H0=H0, omch2=omch2, ombh2=ombh2, omk=0,
                       NonLinear=camb.model.NonLinear_both)

# get the cosmology from CAMB
cosmo = Cosmology.from_camb(pars)

# shells of 200 Mpc in comoving distance spacing
zb = glass.shells.distance_grid(cosmo, 0., 1., dx=200.)

# uniform matter weight function
# CAMB requires linear ramp for low redshifts
ws = glass.shells.tophat_windows(zb, weight=glass.ext.camb.camb_tophat_weight)

# compute angular matter power spectra with CAMB
cls = glass.ext.camb.matter_cls(pars, lmax, ws)

np.save('cls_test.npy', cls)

# load the angular matter power spectra previously computed with CAMB
cls = np.load('cls_test.npy')

# basic parameters of the simulation
nside = lmax = 128

# compute Gaussian cls for lognormal fields for 3 correlated shells
gls = glass.fields.lognormal_gls(cls, nside=nside, lmax=lmax, ncorr=3)

# generator for lognormal matter fields
matter = glass.fields.generate_lognormal(gls, nside, ncorr=3)

# constant galaxy density distribution
z = np.linspace(0., 1., 100)
dndz = np.full_like(z, 0.01)

# make a cube for galaxy number in redshift
zcub = np.linspace(-zb[-1], zb[-1], 21)
cube = np.zeros((zcub.size-1,)*3)

data_collection = []

# simulate and add galaxies in each matter shell to cube
for i, delta_i in enumerate(matter):

    # restrict galaxy distribution to this shell
    z_i, dndz_i = glass.shells.restrict(z, dndz, ws[i])

    # compute galaxy density in this shell
    ngal = np.trapz(dndz_i, z_i)

    # simulate positions from matter density
    for gal_lon, gal_lat, gal_count in glass.points.positions_from_delta(ngal, delta_i):

        # sample redshifts uniformly in shell
        gal_z = glass.galaxies.redshifts_from_nz(gal_count, ws[i].za, ws[i].wa)

        # generate a array
        data_slice = np.column_stack((gal_lon, gal_lat, gal_z))
        
        # collection
        data_collection.append(data_slice)
        
data = np.vstack(data_collection)

print(np.min(data[:, 0]), np.max(data[:, 0]))
```
-------------------------------------
-44.96491726168818 359.99952918353677

**Comment by ntessore** [comment]
Hi, thanks for the excellent question! To draw random positions within HEALPix pixels, the code uses the mapping from HEALPix to the plane described in https://arxiv.org/pdf/astro-ph/0409513. There, if you look at the 12 base pixels of the HEALPix grid (Fig. 2), you see that the interior of the first equatorial base pixel wraps around zero longitude:

<img width="548" alt="image" src="https://github.com/user-attachments/assets/bb5c4bf1-a3e8-4c67-a097-966509e01ca7"> \
<strong><emph>(Image credit: Fig. 2, Górski et al. 2005)</emph></strong>

What you are seeing is therefore a known effect for points falling into that specific base pixel.

Of course, we could wrap the positions manually into the [0.0, 360.0) range. But since it is sometimes useful to have all positions within a pixel be in a compact region, we do not do that currently.

This could be documented better, so thanks again for raising this question.

**Comment by z20230220** [comment]
I understand now. Thank you for your patient explanation.
