### ISSUE TITLE
Use `scipy.cumulative_trapezoid` instead of defining `cumtrapz`?

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#259]
### What is the Topic of Your Question

Usage

### Add Your Question Below

This will reduce maintenance burden, and also testing burden. I am not sure if there is any difference between the functions, but they look almost identical.

**Comment by Saransh-cpp** [comment]
That is a valid point too. I thought of this because `cumtrapz` is not tested in the repository right now. It made me wonder if I should add the tests or just remove the custom implementation.

**Comment by Saransh-cpp** [comment]
I'll close this as not planned.

**Comment by paddyroddy** [comment]
I do feel that this is a valid point. `scipy` will have heavily tested their `cumulative_trapezoid` implementation.

**Comment by Saransh-cpp** [comment]
Given that we are trying not to depend on `scipy` (including possibly removing dependencies that do that), it would make sense to close this issue and keep the custom implementation.
