### ISSUE TITLE
do not convolve matter fields

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#26]
Currently, the matter shell is integrated over HEALPix pixels by multiplying matter Cls with the pixel window function before sampling.

This means that the computed weak lensing fields are also integrated, which is not correct for making galaxy catalogues.

The necessary change is to not compute integrated matter fields, and then apply the convolution when the galaxy number count maps are computed, which is a natural place for that to happen. In the simulation, all fields (matter shell, convergence, shear) are then the continuous fields sampled at the HEALPix pixel centres.

**Comment by arthurmloureiro** [comment]
Does that have implications for simulations with clustering only?
