### ISSUE TITLE
Can replace a few functions with `skypy` functions

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#277]
### What is the Topic of Your Question

Usage

### Add Your Question Below

There are a few functions that are identical to implementations in `skypy` - [`skypy.utils.random.triaxial_axis_ratio`](https://github.com/skypyproject/skypy/blob/ee05b5aba9118663c68fc69ffae523bc0e450e8a/skypy/utils/random.py#L78) <-> [`glass.shapes.triaxial_axis_ratio`](https://github.com/glass-dev/glass/blob/f26c8c8f4b64f2a6752d7e9f75bce52c67b576e8/glass/shapes.py#L35), [`skypy.galaxies.morphology.ryden04_ellipticity`](https://github.com/skypyproject/skypy/blob/ee05b5aba9118663c68fc69ffae523bc0e450e8a/skypy/galaxies/morphology.py#L231) <-> [`glass.shells.ellipticity_ryden04`](https://github.com/glass-dev/glass/blob/f26c8c8f4b64f2a6752d7e9f75bce52c67b576e8/glass/shapes.py#L35), maybe more...

I did not create a new issue for these earlier based on the discussion in #259, but it would be nice to look at these too if the decision changes.

I don't have a strong opinion because even though this is a good thing to do, it will add an extra dependency.

**Comment by ntessore** [comment]
Yep, these are my functions, and their home is in GLASS.

**Comment by Saransh-cpp** [comment]
Ahh, that makes so much, thanks!

**Comment by paddyroddy** [comment]
> Yep, these are my functions, and their home is in GLASS.

Why does `skypy` not use the functions directly from GLASS?
