### ISSUE TITLE
split sampling of positions and redshifts

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#28]
I want to simplify the logic of sampling galaxy positions and redshifts, making them two separate generators.  This means removing support for multiple populations from the generators, since those would need to be matched between the two.  However, there is a much better system in place already in the form of generator groups, so this is no real loss.

**Comment by arthurmloureiro** [comment]
I am a bit confused about the implications of this. 

Would we still be able to simulate multiple tracers?
