### ISSUE TITLE
Add `mypy` for type checking

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#280]
### Is Your Feature Request Related to a Problem? Please Describe

It will be useful for both the users and the developers to have well defined static types for everything in glass. The repository right now does have types in places but they are not tested. These can be tested by adding mypy as a pre-commit hook. Satisfying mypy will also pave the way for experimenting with [mypyc](https://mypyc.readthedocs.io/en/latest/introduction.html) compilations.

Related issues - https://github.com/glass-dev/glass/issues/187. https://github.com/glass-dev/glass/issues/246

**Comment by paddyroddy** [comment]
See #358

**Comment by paddyroddy** [comment]
Closing due to #359, in favour of #358
