### ISSUE TITLE
Update README to point to correct examples

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#286]
### Which Section of the Documentation Needs Improving?

README

### What Can be Improved About This Section

The README still points to the [external examples](https://github.com/glass-dev/glass-examples/) which have been sunset.

### How to Improve This Section

The README should point to the new [in-place examples](https://glass.readthedocs.io/latest/examples.html). There's a question whether this should point to `latest` (good for the repository) or to `stable` (good for the PyPI page, although even better would be pointing to the correct version, which seems a lot of work for very little gain).

**Comment by paddyroddy** [comment]
@ntessore the README on `main` doesn't do this. Are you looking at PyPI? That will be because a release hasn't been made since the change

**Comment by ntessore** [comment]
I mean this link here

https://github.com/glass-dev/glass/blob/94a4718f410f8c82c5b82d9b9e85ba280972ce6d/README.md?plain=1#L47

**Comment by paddyroddy** [comment]
Okay, understood. So it should really point to https://glass.readthedocs.io/stable/examples.html, which doesn't exist yet. I could change it to that now so that it is ready when a release is made?

**Comment by ntessore** [comment]
I wonder if we shouldn't point the README to glass.readthedocs.io/latest in all three places, then put a conditional

    sed -i "s|https://glass.readthedocs.io/latest|https://glass.readthedocs.io/$(git describe --tags)|" README.md

in there when the sdist is built for distribution.
