### ISSUE TITLE
We're not getting coverage status updates in PRs

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#311]
### Describe the Bug

I know we turned off the PR comments (which are annoying), but I'd expect a status check saying the current percentage hit (and the difference). Think this was working previously.

### To Reproduce

```python
import glass
...
```

### Version In Use

N/A

### Additional Context

```markdown
- Python version:
- Operating system:
```

**Comment by Saransh-cpp** [comment]
I can't access the settings on coveralls.

**Comment by Saransh-cpp** [comment]
Working now. For future reference - needed a resync through coveralls dashboard.
