### ISSUE TITLE
`ellipticity_ryden04` has a shape mismatch bug

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#328]
### Describe the Bug

The implementation right now keeps sampling values until it gets all positive values -

https://github.com/glass-dev/glass/blob/2eb3e8bd94adf5f25c67a54fba0484a49c38b212/glass/shapes.py#L142-L151

Let's say if `mu = [-1.85, -2.85]`, `gamma = 0.89`, `gamma = 0.222`, `sigma_gamma = 0.056` -

- `size` = `(2,)`
- `eps.shape` = `(2,)`
- `rng.normal(mu, sigma)` will have the shape `(2,)` because numpy broadcasts the parameters internally

If one value in `eps` is `bad` (`<0`) -

- `bad` = `[True, False]`
- `eps[bad].shape` = `(1,)`

then this will not work - 

```py
eps[bad] = rng.normal(mu, sigma, size=eps[bad].shape)
```

as a `(2,)` array cannot be resized to `(1,)`.

---

This bug was hidden by the `float value is not indexable` error when the broadcasting rule was not present.

I am not sure what should be done here. Should we consider using something like truncated normal here?

### To Reproduce

```python
from glass import ellipticity_ryden04


while True:
    ellipticity_ryden04([-1.85, -2.85], 0.89, 0.222, 0.056)  # rerun till it errors out
```

### Expected Behaviour

No shape mismatch error.

### Actual Behaviour

```py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
      1 while True:
----> 2     ellipticity_ryden04([-1.85, -2.85], 0.89, 0.222, 0.056)

File ~/Code/UCL/glass/glass/shapes.py:146, in ellipticity_ryden04(mu, sigma, gamma, sigma_gamma, size, rng)
    144 bad = eps > 0
    145 while np.any(bad):
--> 146     eps[bad] = rng.normal(mu, sigma, size=eps[bad].shape)
    147     bad = eps > 0
    148 gam = rng.normal(gamma, sigma_gamma, size=size)

File numpy/random/_generator.pyx:1288, in numpy.random._generator.Generator.normal()

File _common.pyx:621, in numpy.random._common.cont()

File _common.pyx:539, in numpy.random._common.cont_broadcast_2()

File _common.pyx:250, in numpy.random._common.validate_output_shape()

ValueError: Output size (1,) is not compatible with broadcast dimensions of inputs (2,).
```

### Version In Use

main

### Additional Context

```markdown
- Python version: 3.11
- Operating system: macOS
```

**Comment by ntessore** [comment]
`bad = np.where(eps > 0)` ?
