### ISSUE TITLE
The code using `cls` - a Python builtin - to represent `C_{\ell}` in cosmology

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#329]
### Describe the Bug

This could have unintended consequences. It is certainly confusing my IDE no end. I suggest we change this, perhaps to `c_l` or even `cl` would be fine, just not `cls`.

### To Reproduce

```python
import glass
...
```

### Version In Use

N/A

### Additional Context

```markdown
- Python version:
- Operating system:
```

**Comment by ntessore** [comment]
Unfortunate, but this is too established a convention to change.
