### ISSUE TITLE
Fix `intersphinx` for the `cosmology` package

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#350]
### What is the Topic of Your Question

Documentation

### Add Your Question Below

Following #347 we now have static types rendering in the documentation. However, as can be seen in the screenshot, `npt.NDArray` isn't highlighted. Anyone know if it's possible?

![Image](https://github.com/user-attachments/assets/dc20a2ec-a51c-4267-b1dc-8fad14c527b9)

**Comment by Saransh-cpp** [comment]
`intersphinx` does this, but we will need to `import numpy.typing` in every file without the `TYPE_CHECKING` condition (https://github.com/sphinx-doc/sphinx/issues/10746), or figure out a way to do that on the fly by writing a custom extension (see https://github.com/pybamm-team/PyBaMM/tree/develop/docs/sphinxext for instance).

**Comment by Saransh-cpp** [comment]
Given the files have a "non-conditional" import of `numpy.typing`, some of the docs render (ugly imo) cross-references to `numpy` types -

<img width="754" alt="image" src="https://github.com/user-attachments/assets/387d77e9-4486-4c7f-8b77-f7ca539e0e88">

Should we should stick to one thing? Either import `numpy.typing` without a condition or with. If we want to add the condition, we can move the types declared in this file to a utility file (`_typeutils.py` or something).

_Originally posted by @Saransh-cpp in https://github.com/glass-dev/glass/pull/347#discussion_r1795879501_

**Comment by paddyroddy** [comment]
So looking into this, it has nothing to do with `TYPE_CHECKING`. It's look alright as of #381. However, I'm trying to work out how to get it working for the [cosmology package](https://cosmology.readthedocs.io/en/stable), which doesn't seem to work out the box.

**Comment by paddyroddy** [comment]
So looks like everything is working except https://cosmology.readthedocs.io/en/stable. I tried both

```python
intersphinx_mapping = {
    "cosmology": ("https://cosmology.readthedocs.io/en/stable", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "python": ("https://docs.python.org/3", None),
}
```

and

```python
intersphinx_mapping = {
    "cosmology": (
        "https://cosmology.readthedocs.io/en/stable",
        "https://cosmology.readthedocs.io/en/stable/objects.inv",
    ),
    "numpy": ("https://numpy.org/doc/stable", None),
    "python": ("https://docs.python.org/3", None),
}
```

any ideas?

**Comment by Saransh-cpp** [comment]
I am tempted to move away from `cosmology` as soon as possible. The move will also help us with Array API stuff. We can maybe discuss this in the Monday meeting.

**Comment by paddyroddy** [comment]
I'm going to close this. We can come back to it if we have issues with #124.
