### ISSUE TITLE
Latex blocks are somehow broken in the `latest` docs

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#352]
### Which Section of the Documentation Needs Improving?

See the docstring of https://glass.readthedocs.io/latest/reference/shells.html#glass.partition

![Image](https://github.com/user-attachments/assets/af50cd88-438e-4890-9f99-be179109f563)

### What Can be Improved About This Section

Fix latex :(

**Comment by ntessore** [comment]
Working: https://glass--237.org.readthedocs.build/237/reference/shells.html#glass.shells.partition
Broken: https://glass--241.org.readthedocs.build/241/reference/shells.html#glass.partition
