### ISSUE TITLE
Latest version rendered on readthedocs is wrong

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#353]
### Which Section of the Documentation Needs Improving?

![Image](https://github.com/user-attachments/assets/34111f29-a81f-44c2-970a-ba3422495a0a)

### What Can be Improved About This Section

Either this is due to https://setuptools-scm.readthedocs.io/en/latest/usage/#usage-from-sphinx

Or readthedocs is not fetching the entire git history for `hatch_vcs` to act on it properly.

**Comment by ntessore** [comment]
I am fairly sure this is new behaviour.

**Comment by paddyroddy** [comment]
> Working: https://glass--262.org.readthedocs.build/262/ Broken: https://glass--263.org.readthedocs.build/263/

But that doesn't make sense as #263 is just adding tests

**Comment by Saransh-cpp** [comment]
I think this is because readthedocs only fetches the latest 50 commits (and the tags associated with them) -

![Image](https://github.com/user-attachments/assets/fd00a3c0-f505-4e8a-b8ec-9c108fecab72)

We have 80+ commits since the past release. Can we update this number on readthedocs? Otherwise we should wait for the release to check if this is fixed.

**Comment by ntessore** [comment]
Great detective work @Saransh-cpp! See https://docs.readthedocs.io/en/latest/build-customization.html#unshallow-git-clone

**Comment by ntessore** [comment]
Although for the sake of faster docs builds, we might just want to create a new release, as you suggest.

**Comment by Saransh-cpp** [comment]
Yes, we are in the position of creating a new release, so I'll just close this and re-open if it is not fixed.
