### ISSUE TITLE
Review "ruff-format recommended" ignore rules

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#362]
### Add your issue here

At the moment, we have several "ruff-format recommended" ignored rules in `pyproject.toml` -

https://github.com/glass-dev/glass/blob/cfe3245785164e4bfff9bb1786230960529237d1/pyproject.toml#L132

It would be good to review these and remove the ones that are not required to be ignored.

**Comment by paddyroddy** [comment]
The reason why I only had those two is that the warning only refers to those

> warning: The following rules may cause conflicts when used with the formatter: `COM812`, `ISC001`. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding them to the `ignore` configuration.

**Comment by Saransh-cpp** [comment]
Keeping all of them ignored shouldn't be bad, but I don't have any strong opinions here. I can revert it back to the old state or just close this issue as resolved 👀

**Comment by paddyroddy** [comment]
I think leave it, and leave the issue open
