### ISSUE TITLE
`test_ellipticity_gaussian` is flaky

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#363]
### Add your issue here

See the failing workflows on main - 
- https://github.com/glass-dev/glass/actions/runs/11345132033/job/31551339600
- https://github.com/glass-dev/glass/actions/runs/11329143777/job/31503990664

I think we should just increase the tolerance.

**Comment by ntessore** [comment]
In the past, I have used https://github.com/pytest-dev/pytest-rerunfailures for these kinds of random tests.

**Comment by Saransh-cpp** [comment]
Might be an overkill for a simple fix, but can look into this. (Looks very useful in such cases tho!)

@paddyroddy do you have any opinions on this?
