### ISSUE TITLE
Produce and upload HTML artifacts of the notebook runs

### ISSUE THREAD

**Issue by Saransh-cpp** [glass-dev/glass#365]
### Add your issue here

> Unrelated to this PR, but we should tweak the "Test examples" action to not just run the examples, but also produce and upload HTML artefacts of the results.

_Originally posted by @ntessore in https://github.com/glass-dev/glass/issues/345#issuecomment-2413721226_

I think it would be better to get rid off the "Test examples" session and just run them on readthedocs, given that one has to pre-run the notebooks in order for them to show up with good outputs on readthedocs.

**Comment by ntessore** [comment]
We spent quite a lot of effort originally to not have the notebooks render on RTD, since that was unbearably slow.

What I meant was simply to replace

    jupyter execute examples/**/*.ipynb

with

    jupyter nbconvert --to html --embed-images --execute examples/**/*.ipynb

and then upload the resulting HTML files with the GitHub action.

**Comment by Saransh-cpp** [comment]
The uploading HTML part is not very clear to me. Do you mean automatically committing the generated HTML output and pushing it to the GLASS repository? But that will not show up on readthedocs. I don't think there is a way to push to readthedocs?

**Comment by ntessore** [comment]
I just meant

```yaml
- uses: actions/upload-artifact@v4
  with:
    path: examples/*.html
```

so we can check the outputs from the test run if necessary (since we are recomputing the examples anyway).

**Comment by ntessore** [comment]
In the future, we could a) recompute the example notebooks in place, and fail the test if the outputs change, and b) have an automated way to recompute the examples. But neither is relevant _right now_ for what we need to do.

**Comment by Saransh-cpp** [comment]
Ahh, now I understand it better, thanks!
