### ISSUE TITLE
Improve docstring return output with typing in `sphinx`

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#375]
In addition, just now I experimented a bit with https://github.com/tox-dev/sphinx-autodoc-typehints and this could provide the kind of annotation we would like to see:

```py
def vmap_galactic_ecliptic(
    nside: int,
    galactic: tuple[float, float] = (30, 90),
    ecliptic: tuple[float, float] = (20, 80),
) -> npt.NDArray[typing.Any]:
    """
    ...

    Returns
    -------
    A HEALPix :term:`visibility map`.

    """
```

Which produces:

<img width="744" alt="image" src="https://github.com/user-attachments/assets/7af19061-758f-40d2-9ac4-8dd1d04bb28b">

_Originally posted by @ntessore in https://github.com/glass-dev/glass/issues/373#issuecomment-2419856894_

**Comment by ntessore** [comment]
I'm happy to experiment with this

**Comment by paddyroddy** [comment]
@ntessore I'm looking at this as part of #188, have got something like:

![Image](https://github.com/user-attachments/assets/710f063e-e684-41e6-94de-2d1d9c9c5368)

```py
# -- autodoc -----------------------------------------------------------------

autodoc_typehints = "description"


# -- napoleon ----------------------------------------------------------------

napoleon_google_docstring = False
napoleon_use_rtype = False


# -- sphinx-autodoc-typehints ----------------------------------------------------------------

always_use_bars_union = True
typehints_use_rtype = False
typehints_defaults = "comma"
```

with these settings, but I can't work out how to get rid of the redundant `Returns`... Any idea?

**Comment by ntessore** [comment]
To be honest, I am starting to think perhaps this is a feature, not a bug. For simple return types, this isn't the worst output:

    Returns:
      The value of the thing.

    Return type:
      int

Whereas for complicated situations, having both sections allows for much more nuance:

    Returns:
      - a (int) -- The value of a. Only returned if return_a is true.
      - b (float) -- The value of b. Only returned if return_b is true.
      - c (bool) -- The value of c. Only returned if return_c is true.

    Return type:
      <some complicated mess that is impossible to understand, ideally suppressed>

**Comment by ntessore** [comment]
Perhaps a good question to answer first is whether the documentation of [`from_convergence()`](https://glass.readthedocs.io/latest/reference/lensing.html#glass.from_convergence) can be made human-readable using a number of `@typing.overload`?

**Comment by paddyroddy** [comment]
Discussed in a call. Going to keep `Returns` and `Return type`. Can be addressed again in the future if we want.
