### ISSUE TITLE
We currently rely on the `cosmology` package which has been archived

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#377]
### Describe the Bug

I'm aware this is on our organisation, but if it's in active use it shouldn't really be archived https://github.com/glass-dev/cosmology

### To Reproduce

import glass
...

### Version In Use

N/A

### Additional Context

- Python version:
- Operating system:

**Comment by Saransh-cpp** [comment]
Duplicate of #124?

**Comment by paddyroddy** [comment]
> Duplicate of [#124](https://github.com/glass-dev/glass/issues/124)?

Yeah, good spot
