### ISSUE TITLE
Investigate Array API compliance

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#383]
### Is Your Feature Request Related to a Problem? Please Describe

First step towards #67. Need to look at which functions look trivial to port, and which don't. To be discussed on the 11th November meeting.

**Comment by Saransh-cpp** [comment]
Here are my thoughts. I could be wrong in categorizing the functions that depend on external libraries (`healpy`, `healpix`, `cosmology`, and `gaussiancl`).

cc: @paddyroddy @ntessore 

## Straightforward

- [ ] `core.algorithm.nnls`
---
- [ ] `core.array.broadcast_first`
- [ ] `core.array.broadcast_leading_axes`
- [ ] `core.array.ndinterp`
- [ ] `core.array.trapz_product`
- [ ] `core.array.cumtrapz`
---
- [ ] `fields.iternorm`
- [ ] `fields.cls2cov`
- [ ] `fields.multalm`
- [ ] `fields.getcl`
- [ ] `fields.effective_cls`
---
- [ ] `shells.RadialWindow`
- [ ] `shells.tophat_windows`
- [ ] `shells.linear_windows`
- [ ] `shells.cubic_windows`
- [ ] `shells.restrict`
- [ ] `shells.partition`
- [ ] `shells.partition_lstsq`
- [ ] `shells.partition_nnls`
- [ ] `shells.partition_restrict`
- [ ] `shells.redshift_grid`
- [ ] `shells.combine`
---
- [ ] `points.effective_bias`
- [ ] `points.linear_bias`
- [ ] `points.loglinear_bias`
- [ ] `points.position_weights`
---
- [ ] `observations.gaussian_nz`
- [ ] `observations.smail_nz`
- [ ] `observations.fixed_zbins`
- [ ] `observations.equal_dens_zbins`
- [ ] `observations.tomo_nz_gausserr`
- [ ] `observations.deflect`

## Requires efforts

### Uses RNGs

- [ ] `fields.generate_gaussian`
---
- [ ] `shapes.triaxial_axis_ratio`
- [ ] `shapes.ellipticity_gaussian`
- [ ] `shapes.ellipticity_intnorm`
- [ ] `shapes.ellipticity_ryden04`
---
- [ ] `points.uniform_positions`
---
- [ ] `galaxies.redshifts`
- [ ] `galaxies.redshifts_from_nz`
- [ ] `galaxies.gaussian_phz`

### Uses healpy

- [ ] `fields.discretized_cls`
---
- [ ] `observations.vmap_galactic_ecliptic`
---
- [ ] `lensing.from_convergence`
- [ ] `lensing.shear_from_convergence`

### Uses healpy and RNGs

- [ ] `fields.generate_lognormal`

### Uses healpix

- [ ] `points.positions_from_delta`
---
- [ ] `galaxies.galaxy_shear`

## Impossible

### Uses gaussiancl->transformcl->flt

Would prefer a decision by the PIs before working on these

- [ ] `fields.transform_cls`
- [ ] `fields.lognormal_gls`

### Uses cosmology

would prefer migrating to `cosmology.api` before working on these

- [ ] `shells.distance_weight`
- [ ] `shells.volume_weight`
- [ ] `shells.density_weight`
- [ ] `shells.distance_grid`
---
- [ ] `galaxies.kappa_ia_nla`
- [ ] `galaxies.MultiPlaneConvergence`
- [ ] `galaxies.MultiPlaneConvergence`
- [ ] `galaxies.multi_plane_matrix`
- [ ] `galaxies.multi_plane_weights`

**Comment by paddyroddy** [comment]
Have created #401, #402, #403, #404 to discuss and tackle this

**Comment by paddyroddy** [comment]
Re-opening so we can tick easier @connoraird
