### ISSUE TITLE
Hide `kappa_ia_nla`

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#399]
### Describe the Bug

Clearly between #21 being raised and merged, https://github.com/glass-dev/cosmology changed its functionality. For now, we will hide this from the users.

### To Reproduce

```python
import glass
...
```

### Version In Use

2024.2.dev122+g663f80a.d20241108

### Additional Context

```markdown
- Python version:
- Operating system:
```

**Comment by Saransh-cpp** [comment]
We should create an issue to un-hide this function once things start working (just to ensure that we don't forget its existence).

**Comment by paddyroddy** [comment]
Good idea
