### ISSUE TITLE
Single-line yields render as parameter names in docs

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#418]
Fantastic effort, particularly with the many changes in specs! There is a remaining issue with single-line yields but it's so minuscule that I want to tackle it separately. Towards a new release!

_Originally posted by @ntessore in https://github.com/glass-dev/glass/pull/381#pullrequestreview-2433892737_

**Comment by ntessore** [comment]
Single-line returns without variable names appear to be special-cased, so this probably requires to give all yields a `name:` line. Low priority.
