### ISSUE TITLE
Can't deploy to TestPyPI

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#421]
### Describe the Bug

The credentials aren't set correctly. Found in #416.

### To Reproduce

```python
import glass
...
```

### Version In Use

N/A

### Additional Context

```markdown
- Python version:
- Operating system:
```

**Comment by ntessore** [comment]
To prevent mistakes, the publishing environment is only allowed on `v*` tags, and I wouldn't want to change that.

It makes more sense to me to create a "Test Release" workflow without that protection than to remove the protection. It would be way too easy to inadvertently select "pypi" in the workflow-dispatch.

**Comment by paddyroddy** [comment]
Okay, well we need to change the CI then
