### ISSUE TITLE
`shells.distance_grid` should call `shells.redshift_grid`

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#456]
### Is Your Feature Request Related to a Problem? Please Describe

The contents of `shells.redshift_grid` are entirely contained within `shells.distance_grid`, so it makes sense to combine them.

**Comment by ntessore** [comment]
This must be an artefact of testing, since `redshift_grid()` is always equi-spaced in redshift, and `distance_grid()` is always equi-spaced in comoving distance, and there's a non-linear cosmological distance law to convert between them.

**Comment by paddyroddy** [comment]
> This must be an artefact of testing, since `redshift_grid()` is always equi-spaced in redshift, and `distance_grid()` is always equi-spaced in comoving distance, and there's a non-linear cosmological distance law to convert between them.

Not sure if I follow. Are you saying that they shouldn't be combined? Have a look at the code, this might have been an oversight.

**Comment by ntessore** [comment]
Sorry, my mistake, I didn't see the PR before. I thought this issue was saying `distance_grid(*args) == cosmo.comoving_distance(redshift_grid(*args))`.
