### ISSUE TITLE
`nox` is missing `--inplace` so HTML artefacts never change

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#460]
This surprised me, so I had a look. I guess you used our noxfile ... where we forgot to add the `--inplace` flag to the `jupyter execute` so that the execution actually changes the notebooks! At the moment, the notebooks run, but their outputs aren't stored anywhere (and our examples' HTML artefacts therefore never change). That's on me, I should have picked up on it in #367.

_Originally posted by @ntessore in https://github.com/glass-dev/glass/issues/425#issuecomment-2504931387_

**Comment by Saransh-cpp** [comment]
Ah, I see it now!
