### ISSUE TITLE
output arrays are changed in place

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#6]
Some arrays, such as the `kappa` maps in `glass.lensing.convergence`, are outputs that are later modified in place. This is potentially an issue if users make a shallow copy of the results.

It needs investigation whether the efficiency gained by modifying the outputs in place is enough to warrant this becoming a common issue.

**Comment by arthurmloureiro** [comment]
How do you avoid this issue?
`to_save.append(shell['kappa'].copy())` ?
